### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by oliver-zhou** [Azure-for-Startups/Content#5]
Just FYI - 

Many links are broken on the README.md: 

i.e., : 
![image](https://cloud.githubusercontent.com/assets/906828/24171727/d6416ce2-0e42-11e7-9374-9a0ca2c4d685.png)

Thus, creating links to https://azure.microsoft.com/en-us/pricing/member-offers/bizspark-startups/)**

instead of 

https://azure.microsoft.com/en-us/pricing/member-offers/bizspark-startups/

The formatting needs to be changed.

**Comment by jurgbonnofsky** [comment]
Thank you for submitting this issue.  It appears that GitHub changed how some default links work.  All links were correctly displaying for many months.  In any case, the issue has been fixed.  Appreciate the reported issue!
